name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

#dependency_overrides:
#  firebase_core: ^2.5.0
#  firebase_core_platform_interface: ^4.5.3
#  modal_bottom_sheet:
#    git:
#      url: https://github.com/danReynolds/modal_bottom_sheet.git
#      path: modal_bottom_sheet


dev_dependencies:
  flutter_test:
    sdk: flutter



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/image-1-bg.png
    - assets/page-1/images/addphotoalternate.png
    - assets/page-1/images/image-1-bg-CS5.png
    - assets/page-1/images/nature.png
    - assets/page-1/images/zoomin.png
    - assets/page-1/images/texture.png
    - assets/page-1/images/nature-vCh.png
    - assets/page-1/images/frame-8.png
    - assets/page-1/images/upgrade.png
    - assets/page-1/images/nature-KoX.png
    - assets/page-1/images/palette.png
    - assets/page-1/images/addphotoalternate-Ed7.png
    - assets/page-1/images/nature1-xcH.png
    - assets/page-1/images/layers.png
    - assets/page-1/images/texture-gmf.png
    - assets/page-1/images/upgrade-hUM.png
    - assets/page-1/images/attachment.png
    - assets/page-1/images/attachment-yaH.png
    - assets/page-1/images/frame-17.png
    - assets/page-1/images/nature-UDF.png
    - assets/page-1/images/frame-1.png
    - assets/page-1/images/nature1.png
    - assets/page-1/images/frame-13.png
    - assets/page-1/images/fluorescent.png
    - assets/page-1/images/frame-17-tf3.png
    - assets/page-1/images/frame-13-vKT.png
    - assets/page-1/images/frame-1-q3F.png
    - assets/page-1/images/auto-group-puxj.png
    - assets/page-1/images/layers-62D.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/nature-WZf.png
    - assets/page-1/images/frame-17-fE1.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/palette-tFB.png
    - assets/page-1/images/frame-10.png
    - assets/page-1/images/layers-iVX.png
    - assets/page-1/images/palette-3E9.png
    - assets/page-1/images/zoomin-URF.png
    - assets/page-1/images/arrowdropdown.png
    - assets/page-1/images/arrowcircleright.png
    - assets/page-1/images/texture-bFf.png
    - assets/page-1/images/fluorescent-W6D.png
    - assets/page-1/images/nature-Bfw.png
    - assets/page-1/images/arrowdropdown-Xof.png
    - assets/page-1/images/frame-13-ri5.png
    - assets/page-1/images/frame-13-MW9.png
    - assets/page-1/images/palette-YFj.png
    - assets/page-1/images/image-1-bg-PTo.png
    - assets/page-1/images/radiobuttonunchecked.png
    - assets/page-1/images/fluorescent-N9o.png
    - assets/page-1/images/auto-group-ae9b.png
    - assets/page-1/images/addphotoalternate-RBX.png
    - assets/page-1/images/simcarddownload.png
    - assets/page-1/images/frame-10-jnR.png
    - assets/page-1/images/nature1-wow.png
    - assets/page-1/images/nature-WR7.png
    - assets/page-1/images/auto-group-yhzp.png
    - assets/page-1/images/frame-17-Rmb.png
    - assets/page-1/images/attachment-MNH.png
    - assets/page-1/images/upgrade-2gh.png
    - assets/page-1/images/frame-1-UY1.png
    - assets/page-1/images/zoomin-prm.png
    - assets/page-1/images/frame-11.png
    - assets/page-1/images/texture-XHK.png
    - assets/page-1/images/frame-11-kDw.png
    - assets/page-1/images/addphotoalternate-9z9.png
    - assets/page-1/images/radiobuttonunchecked-jay.png
    - assets/page-1/images/frame-13-oFP.png
    - assets/page-1/images/upgrade-Lo3.png
    - assets/page-1/images/zoomin-S9F.png
    - assets/page-1/images/nature1-WqF.png
    - assets/page-1/images/palette-bZB.png
    - assets/page-1/images/frame-17-4f3.png
    - assets/page-1/images/nature1-G8q.png
    - assets/page-1/images/frame-8-RrH.png
    - assets/page-1/images/nature-Pc5.png
    - assets/page-1/images/image-1-bg-aru.png
    - assets/page-1/images/fluorescent-9tM.png
    - assets/page-1/images/texture-YBj.png
    - assets/page-1/images/colors.png
    - assets/page-1/images/texture-H4m.png
    - assets/page-1/images/texture-adX.png
    - assets/page-1/images/auto-group-5q4h.png
    - assets/page-1/images/zoomin-tt9.png
    - assets/page-1/images/frame-17-xWd.png
    - assets/page-1/images/attachment-oEh.png
    - assets/page-1/images/palette-Yxy.png
    - assets/page-1/images/frame-1-Weu.png
    - assets/page-1/images/addphotoalternate-MFf.png
    - assets/page-1/images/nature-5xM.png
    - assets/page-1/images/auto-group-czk1.png
    - assets/page-1/images/frame-1-cgZ.png
    - assets/page-1/images/arrowcircleleft.png
    - assets/page-1/images/frame-10-rL1.png
    - assets/page-1/images/frame-1-C8y.png
    - assets/page-1/images/image-1-bg-hV3.png
    - assets/page-1/images/draghandle.png
    - assets/page-1/images/zoomin-RK7.png
    - assets/page-1/images/frame-17-WFK.png
    - assets/page-1/images/frame-10-TwF.png
    - assets/page-1/images/colors-Uqf.png
    - assets/page-1/images/attachment-xVw.png
    - assets/page-1/images/filter.png
    - assets/page-1/images/frame-8-Ygy.png
    - assets/page-1/images/filter-ySq.png
    - assets/page-1/images/layers-mhT.png
    - assets/page-1/images/frame-8-hwf.png
    - assets/page-1/images/filter-TQu.png
    - assets/page-1/images/nature-nTB.png
    - assets/page-1/images/frame-1-XvZ.png
    - assets/page-1/images/auto-group-8fjv.png
    - assets/page-1/images/filter-QoB.png
    - assets/page-1/images/fluorescent-ar5.png
    - assets/page-1/images/nature1-98V.png
    - assets/page-1/images/image-1-RRK.png
    - assets/page-1/images/auto-group-fxt7.png
    - assets/page-1/images/draghandle-1dj.png
    - assets/page-1/images/draghandle-NDP.png
    - assets/page-1/images/frame-10-Xc5.png
    - assets/page-1/images/frame-4.png
    - assets/page-1/images/layers-Cwb.png
    - assets/page-1/images/draghandle-JDF.png
    - assets/page-1/images/palette-KPF.png
    - assets/page-1/images/zoomin-KXf.png
    - assets/page-1/images/frame-10-sxV.png
    - assets/page-1/images/filter-ac1.png
    - assets/page-1/images/frame-8-kWV.png
    - assets/page-1/images/frame-10-4fb.png
    - assets/page-1/images/attachment-pem.png
    - assets/page-1/images/nature-nbb.png
    - assets/page-1/images/upgrade-kYR.png
    - assets/page-1/images/frame-8-ik9.png
    - assets/page-1/images/upgrade-j9T.png
    - assets/page-1/images/frame-10-smT.png
    - assets/page-1/images/fluorescent-pwb.png
    - assets/page-1/images/layers-R5T.png
    - assets/page-1/images/draghandle-EH7.png
    - assets/page-1/images/frame-11-zBj.png
    - assets/page-1/images/upgrade-B6H.png
    - assets/page-1/images/frame-17-p2m.png
    - assets/page-1/images/layers-pNM.png
    - assets/page-1/images/fluorescent-tYZ.png
    - assets/page-1/images/frame-1-zAu.png
    - assets/page-1/images/frame-10-Wn5.png
    - assets/page-1/images/frame-1-ZJH.png
    - assets/page-1/images/texture-Hwf.png
    - assets/page-1/images/frame-8-43s.png
    - assets/page-1/images/addphotoalternate-sZ3.png
    - assets/page-1/images/frame-6.png
    - assets/page-1/images/upgrade-XYV.png
    - assets/page-1/images/palette-X4d.png
    - assets/page-1/images/frame-7.png
    - assets/page-1/images/frame-8-4X3.png
    - assets/page-1/images/layers-Edo.png
    - assets/page-1/images/image-1-bg-iv5.png
    - assets/page-1/images/frame-1-UPT.png
    - assets/page-1/images/delete.png
    - assets/page-1/images/attachment-XAh.png
    - assets/page-1/images/zoomin-o1j.png
    - assets/page-1/images/frame-11-yR3.png
    - assets/page-1/images/frame-17-uA1.png
    - assets/page-1/images/upgrade-3g5.png
    - assets/page-1/images/attachment-YFT.png
    - assets/page-1/images/image-1-bg-QRX.png
    - assets/page-1/images/frame-1-6ty.png
    - assets/page-1/images/attachment-np1.png
    - assets/page-1/images/palette-jsf.png
    - assets/page-1/images/frame-8-UkR.png
    - assets/page-1/images/layers-gh7.png
    - assets/page-1/images/fluorescent-Nth.png
    - assets/page-1/images/frame-11-rt1.png
    - assets/page-1/images/auto-group-qbpj.png
    - assets/page-1/images/frame-1-ZQu.png
    - assets/page-1/images/frame-10-4do.png
    - assets/page-1/images/layers-aMo.png
    - assets/page-1/images/add.png
    - assets/page-1/images/upgrade-JEd.png
    - assets/page-1/images/attachment-BSq.png
    - assets/page-1/images/frame-1-tXb.png
    - assets/page-1/images/zoomin-RJZ.png
    - assets/page-1/images/fluorescent-P6H.png
    - assets/page-1/images/frame-8-J6m.png
    - assets/page-1/images/frame-17-NoK.png
    - assets/page-1/images/zoomin-CQy.png
    - assets/page-1/images/image-1-7bo.png
    - assets/page-1/images/frame-2.png
    - assets/page-1/images/colors-FR3.png
    - assets/page-1/images/fluorescent-t6d.png
    - assets/page-1/images/frame-10-RUV.png
    - assets/page-1/images/layers-5J9.png
    - assets/page-1/images/palette-5oF.png
    - assets/page-1/images/frame-8-Sdo.png
    - assets/page-1/images/texture-rMP.png
    - assets/page-1/images/upgrade-2Mf.png
    - assets/page-1/images/frame-17-RRj.png
    - assets/page-1/images/image-1-bg-6Lh.png
    - assets/page-1/images/palette-gJu.png
    - assets/page-1/images/brush.png
    - assets/page-1/images/texture-qbf.png
    - assets/page-1/images/image-1-bg-tbs.png
    - assets/page-1/images/palette-Xsf.png
    - assets/page-1/images/attachment-5eH.png
    - assets/page-1/images/colors-eBb.png
    - assets/page-1/images/zoomin-LyX.png
    - assets/page-1/images/frame-12.png
    - assets/page-1/images/palette-kvd.png
    - assets/page-1/images/frame-8-kt1.png
    - assets/page-1/images/fluorescent-Xi1.png
    - assets/page-1/images/frame-1-gqo.png
    - assets/page-1/images/zoomin-pSD.png
    - assets/page-1/images/layers-4Hw.png
    - assets/page-1/images/image-1-ia5.png
    - assets/page-1/images/brush-jeH.png
    - assets/page-1/images/frame-12-4ZP.png
    - assets/page-1/images/nature-897.png
    - assets/page-1/images/upgrade-Aqo.png
    - assets/page-1/images/frame-10-Ecq.png
    - assets/page-1/images/palette-HSR.png
    - assets/page-1/images/edit.png
    - assets/page-1/images/colors-Wvu.png
    - assets/page-1/images/frame-17-RA1.png
    - assets/page-1/images/upgrade-PkM.png
    - assets/page-1/images/share.png
    - assets/page-1/images/delete-dz1.png
    - assets/page-1/images/frame-1-JTB.png
    - assets/page-1/images/nature-LHo.png
    - assets/page-1/images/palette-XwF.png
    - assets/page-1/images/add-X9B.png
    - assets/page-1/images/frame-8-5LM.png
    - assets/page-1/images/nature-LDf.png
    - assets/page-1/images/attachment-KGV.png
    - assets/page-1/images/image-1-7ih.png
    - assets/page-1/images/frame-1-sz1.png
    - assets/page-1/images/upgrade-jqs.png
    - assets/page-1/images/zoomin-V4M.png
    - assets/page-1/images/colors-b2q.png
    - assets/page-1/images/upgrade-rzM.png
    - assets/page-1/images/nature-HsF.png
    - assets/page-1/images/frame-1-hvy.png
    - assets/page-1/images/zoomin-tdP.png
    - assets/page-1/images/layers-P4M.png
    - assets/page-1/images/frame-10-wJ9.png
    - assets/page-1/images/frame-16.png
    - assets/page-1/images/frame-10-m7o.png
    - assets/page-1/images/frame-17-hKX.png
    - assets/page-1/images/fluorescent-3eH.png
    - assets/page-1/images/frame-11-yXw.png
    - assets/page-1/images/delete-f9s.png
    - assets/page-1/images/brush-rfb.png
    - assets/page-1/images/layers-cem.png
    - assets/page-1/images/edit-aLh.png
    - assets/page-1/images/frame-8-L4y.png
    - assets/page-1/images/texture-zfK.png
    - assets/page-1/images/attachment-vos.png
    - assets/page-1/images/image-1-bg-fuB.png
    - assets/page-1/images/fluorescent-9Gm.png
    - assets/page-1/images/addphotoalternate-xTK.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

